### PR TITLE
Updated for moving functionality to nat, please see: https://github.c…

### PR DESCRIPTION
**Pull request by SridharJagannathan**
PR implemented as part of moving functionality to `nat`, please see: https://github.com/natverse/nat/pull/424

### CODE REVIEW

**Comment by SridharJagannathan** [comment]
@jefferis Can you please merge this too, after you have completed natverse/nat#424

**Comment by SridharJagannathan** [comment]
The travis build would pass once the `nat`(natverse/nat#424) is merged.

**Comment by jefferis** [comment]
@SridharJagannathan Would it be possible to document the functions/methods that have been moved out of the package? This can be done simply by adding them to https://github.com/natverse/elmr/blob/e37bd62cf29acd5157955b9975809e162df4b6a0/R/deprecated.R. I have done `distal_to` as an example but obviously there were several more.

**Comment by SridharJagannathan** [comment]
@jefferis Thanks for your comments about deprecated functions. I have made a slightly different design and moved them to defunct functions. All defunct functions can now be listed as `help("elmr-defunct")`

**Comment by SridharJagannathan** [comment]
@jefferis I have made the changes as suggested by you. My main question is that in the file `test-ngraph` there is a testcase that tests the function `distal_to` and it runs without any error. But the problem is that now that this function `distal_to` is moved to `nat` ideally this testcase should fail and leave an error?

**Comment by jefferis** [comment]
Thanks @SridharJagannathan! Can you point me to the relevant line in this test-ngraph file?

**Comment by jefferis** [comment]
I've looked at the test file

https://github.com/natverse/elmr/blob/e697104bc731f9c670d5c611b3db52b011d3f711/tests/testthat/test-ngraph.R#L3

The test should pass because

1. elmr depends on nat. 
2. therefore nat::distal_to will be visible (even without the nat:: prefix)
3. the only thing that will fail is if you use elmr::distal_to

Of course the test should really be in nat now, not elmr. But it should pass.

**Pull request merged**
